# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            CySBGN
tagline:          SBGN diagrams in Cytoscape
description:      "SBGN diagrams in Cytoscape"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /cysbgn/
toollogo:         /cysbgn/cysbgn_logo.png

author:
  name:           'Emanuel Goncalves'

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/saezlab/cysbgn

appstore:         http://apps.cytoscape.org/apps/cysbgn
sourceforge:         https://sourceforge.net/projects/cysbgn/
